---
title: "dash-test"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, dev="CairoPNG"}
knitr::opts_chunk$set(dev="CairoPNG")
library(tidyverse)
library(flexdashboard)
library(zoo)
source("FUNCTIONS.R")
```

```{r read_data}
state_cleaned <- readRDS("data/state_raw.rds")%>%
  select(date=1,posTest=2, negTest=5,tests=7,cases=9,admissions=15,discharges=17,currentHosp=21,ICU=23,vent=24,dailyDeaths=25,
         totalDosesPriorDay=29, totalDose1=32, totalDose2=34)%>%
  filter(row_number() >= 11)%>%
  mutate(percentPos = round((cases/tests * 100),1),
         Avg7Day_Cases = movingAvg(cases),
         percentChange_cases = pctChange(Avg7Day_Cases), # USES ROLLING AVG
         Last7Days_100k = round((rollsumr(cases, 7, fill=NA,align='right')) * (100000/1059361),0),
         percentChange_100k = pctChange(Last7Days_100k),
         Avg7Day_Tests = movingAvg(tests),
         Avg7Day_Pos = movingAvg(percentPos, 1),
         percentChange_pos = pctChange(Avg7Day_Pos),
         Avg7Day_Adm = movingAvg(admissions),
         percentChange_adm = pctChange(Avg7Day_Adm),
         Avg7Day_Hosp = movingAvg(currentHosp),
         percentChange_hosp = pctChange(currentHosp), # USES RAW NUMS
         Avg7Day_ICU = movingAvg(ICU),
         percentChange_ICU = pctChange(ICU), # USES RAW NUMS
         Avg7Day_Vent = movingAvg(vent),
         percentChange_vent = pctChange(vent), # USES RAW NUMS
         Avg7Day_Deaths = movingAvg(dailyDeaths),
         totalDosesPriorDay=na_if(totalDosesPriorDay, "--")%>%as.numeric,
         Avg7Day_totalDosesPriorDay=movingAvg(totalDosesPriorDay),
         percentChange_totalDoses = pctChange(Avg7Day_totalDosesPriorDay))

CDC <- readRDS("data/CDC_NE.rds")%>%
  filter(State == "RI")%>%
  select(date, pct)%>%
  mutate(percentChange = pct - lag(pct, 7))
```


Column {}
---

### Daily Cases (7-Day Average vs Last Week)

```{r}
vb_dec(state_cleaned$Avg7Day_Cases, state_cleaned$percentChange_cases, state_cleaned)
```

### Cases per 100,000 (7-Day Sum vs Last Week)

```{r}
vb_dec(state_cleaned$Last7Days_100k, state_cleaned$percentChange_100k, state_cleaned)
```

Column {}
---

### Currently Hospitalized (vs Last Week)

```{r}
vb_hosp(state_cleaned$currentHosp, state_cleaned$percentChange_hosp, state_cleaned)
```

### ICU (vs Last Week)

```{r}
vb_hosp(state_cleaned$ICU, state_cleaned$percentChange_ICU, state_cleaned)
```

### Ventilator (vs Last Week)

```{r}
vb_hosp(state_cleaned$vent, state_cleaned$percentChange_vent, state_cleaned)
```

Column {}
---

### Vaccines (7-Day Average, Doses Administered vs Last Week)

```{r}
vb_inc(state_cleaned$Avg7Day_totalDosesPriorDay, state_cleaned$percentChange_totalDoses, state_cleaned)
```

### % Doses Utilized (vs Last Week)

```{r}
vb_inc(CDC$pct, CDC$percentChange, CDC)
```

