---
title: "test"
author: "/u/computergeek1100"
date: "12/8/2020"
output: html_document
---

##Load Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(zoo)
library(htmlwidgets)
library(plotly)
```

## Graph of daily tests, shaded by pos/neg
```{r}
testData <- stateData%>%
  select(date=1,Positive=2,Negative=5)%>%
  pivot_longer(c(Positive,Negative), names_to="Result",values_to="numTests")
```
```{r}
ggplot(testData,aes(date,numTests,fill=Result))+
  geom_col()
```

## Positivity Comparison
```{r}
PercentPosMethods <- stateData%>%
  select(date=1, m1_pos=2,m2_pos=9,m3_neg=12,total_tests=7)%>%
  mutate(m1_rate = (m1_pos / total_tests) * 100)%>%
  mutate(m2_rate = (m2_pos / total_tests) * 100)%>%
  mutate(m3_rate = (m2_pos / (m2_pos + m3_neg)) * 100)%>%
  pivot_longer(cols=c(m1_rate, m2_rate, m3_rate), names_to = "method", values_to="percentPos")
```

```{r}
ggplot(PercentPosMethods, aes(date, percentPos, color=method))+
  geom_line()+
  scale_color_discrete(name="",labels=c("Method 1 (Total Cases)", "Method 2 (Total People)", "Method 3 (First-Time Tests Only)"))+
  theme(legend.position="bottom")+
  labs(title="Methods to Calculate Test Positivity")
```

## Net Admissions/Discharges
```{r}
ggplot(admissionsData, aes(x=date))+geom_col(aes(y=admissions))+geom_col(aes(y=negDis))+geom_line(aes(y=net))
```

## Web Scraping (Vaccination Data) NOT USED
```{r message=FALSE, warning=FALSE}
rD <- RSelenium::rsDriver(
  browser = "firefox",
  extraCapabilities = list(
    "moz:firefoxOptions" = list(
      args = list('-p webscrape','--headless')
    )
  )
)
```

```{r message=FALSE, warning=FALSE}
remDr <- rD$client
remDr$open()
remDr$navigate("https://datastudio.google.com/u/0/reporting/f95ea2dd-e77a-45dc-9735-f60e8581ff32/page/o9ivB")
```

```{r}
totalDose1 <- remDr$findElement(using='xpath','/html/body/app-bootstrap/ng2-bootstrap/bootstrap/div/div/div/div/div/div[1]/div[2]/div/div[1]/div/div[1]/div/lego-report/lego-canvas-container/div/file-drop-zone/span/content-section/div[3]/canvas-component/div/div/div[1]/div/div/lego-table/div/div[3]/div[1]/div[2]')
totalDose1 <- totalDose1$getElementText()[[1]]

totalDose2 <- remDr$findElement(using='xpath','/html/body/app-bootstrap/ng2-bootstrap/bootstrap/div/div/div/div/div/div[1]/div[2]/div/div[1]/div/div[1]/div/lego-report/lego-canvas-container/div/file-drop-zone/span/content-section/div[3]/canvas-component/div/div/div[1]/div/div/lego-table/div/div[3]/div[2]/div[2]')
totalDose2 <- totalDose2$getElementText()[[1]]

dateUpdated_vax <- remDr$findElement(using="xpath",'/html/body/app-bootstrap/ng2-bootstrap/bootstrap/div/div/div/div/div/div[1]/div[2]/div/div[1]/div/div[1]/div/lego-report/lego-canvas-container/div/file-drop-zone/span/content-section/div[4]/canvas-component/div/div/div[1]/div/div/lego-table/div/div[3]/div/div[2]')
dateUpdated_vax <- dateUpdated_vax$getElementText()[[1]]

vaxVector <- c(dateUpdated_vax, totalDose1, totalDose2)
vaxData <- rbind(vaxData, vaxVector)

vaxDataCleaned <- vaxData

vaxDataCleaned$date <- as.Date(vaxDataCleaned$date, format="%b %d, %Y")
vaxDataCleaned$totalDose1 <- as.numeric(gsub(",","",vaxDataCleaned$totalDose1))
vaxDataCleaned$totalDose2 <- as.numeric(gsub(",","",vaxDataCleaned$totalDose2))
vaxDataCleaned <- vaxDataCleaned %>% 
  mutate(totalDoses = totalDose1+totalDose2,
         dose1PriorDay = totalDose1 - lag(totalDose1),
         dose2PriorDay = totalDose2 - lag(totalDose2),
         totalDosesPriorDay = totalDoses - lag(totalDoses))

vaxData_GRAPH <- vaxDataCleaned%>%
  select(1,3,2,4)%>%
  pivot_longer(c(2:3), names_to = "dose", values_to = "number")
vaxData_GRAPH <- vaxData_GRAPH[-c(1,2),]
```

```{r}
vaxGraph <- ggplot(vaxData_GRAPH, aes(date, number, fill=dose))+
  geom_col(position=position_stack(reverse=TRUE))+
  geom_smooth(aes(date, totalDoses), se=FALSE)+
  labs(title="Total Vaccinated", x = "Date", y = "Total Doses Administered")
ggplotly(vaxGraph)
```


```{r}
vaxData <- data.frame(date=c("Dec 17, 2020", "Dec 18, 2020", "Dec 21, 2020", "Dec 22, 2020", "Dec 23, 2020", "Dec 28, 2020", "Dec 29, 2020", "Dec 30, 2020"), totalDose1=c("0", "1,226","4,827","6,400","7,072","11,935", "12,869","17,020"), totalDose2=c("0","0","0","0","0","0","0","0")) # initialize original df in case of issues
```

```{r}
remDr$close()
# remDr$errorDetails()
rD$server$stop()
```

```{r}
vectorTest <- c("Jan 22, 2021", "52,925", "13,145")
lastRow <- as.character(tail(vaxData,1))
if(all(vectorTest==lastRow)){
  stop("Latest data already scraped")
}else {
  print("Test")
}
```


## Model Vaccination Rate Over Time
```{r}
vaxData2 <- vaxDataCleaned%>%
  mutate(dose1PriorDay = totalDose1 - lag(totalDose1),
         dose2PriorDay = totalDose2 - lag(totalDose2))%>%
  padr::pad()

vaxData2$totalDosesPriorDay[is.na(vaxData2$totalDosesPriorDay)] <- 0
vaxData2$dose1PriorDay[is.na(vaxData2$dose1PriorDay)] <- 0
vaxData2$dose2PriorDay[is.na(vaxData2$dose2PriorDay)] <- 0

vaxData2 <- vaxData2%>%mutate(
  avg7DayTotalDoses = round(rollmean(totalDosesPriorDay, 7, na.pad = TRUE, align="right"), 0),
  avg7DayDose1 = round(rollmean(dose1PriorDay, 7, na.pad = TRUE, align = "right"), 0),
  avg7DayDose2 = round(rollmean(dose2PriorDay, 7, na.pad = TRUE, align = "right"), 0),
  numDaysD1 = (1:nrow(vaxData2)) - 2, # days since 1st vaccine administered
  numDaysD2 = (1:nrow(vaxData2)) - 19)
```

```{r}
ggplot(vaxData2, aes(date, totalDoses))+
  geom_point()+
  geom_line()+
  geom_smooth(formula=y~poly(x, 2), method="lm", se=FALSE)+
  labs(x="Date", y="Total Doses Distributed")
```
```{r}
vaxRate_D1POLY <- lm(totalDose1~poly(numDaysD1,2, raw=TRUE), vaxData2)
vaxRate_D1POLY

vaxRate_D2POLY <- lm(totalDose2~poly(numDaysD2,2, raw=TRUE), vaxData2)
vaxRate_D2POLY

vaxRate_POLY <- lm(totalDoses~poly(numDaysD1,2, raw=TRUE), vaxDataCLEANED_2)
vaxRate_POLY

vaxRate_LOESS <- loess(avg7DayTotalDoses~numDaysD1, vaxData2)
vaxRate_LOESS
```

$$
R_1 = 9.39d^2 + 1168.12d + 956.02\\
R_2 = 17.53d^2 + 373.29d + 1321.84\\
R_t = 9.12d^2 + 1879.57d - 6527.58
$$


## Save average vaccination rate as CSV
```{r}
vaxDataReddit <- vaxDataCleaned%>%
  select(date, totalDoses, totalDosesPriorDay)%>%
  padr::pad()
vaxDataReddit$totalDosesPriorDay[is.na(vaxDataReddit$totalDosesPriorDay)] <- 0
vaxDataReddit <- vaxDataReddit%>%mutate(avg7day = round(rollmean(totalDosesPriorDay, 7, na.pad=TRUE, align='right'),0))

write.csv(vaxDataReddit, "../graphs/reddit/vaxData_avg.csv")
```


## CUSTOM FUNCTIONS
```{r}
ggArgs <- function(gg, lab1 = NULL, lab2 = NULL){
  plt <- ggplotly(gg, tooltip="text",dynamicTicks=TRUE, originalData=FALSE)%>%
    config(displayModeBar=FALSE)%>%
    layout(yaxis=list(rangemode="tozero"))
  if(!is.null(lab1) & !is.null(lab2)){
    plt$x$data[[1]]$name <- lab1
    plt$x$data[[2]]$name <- lab2
  }
  return(plt)
}

widgetArgs <- function(plt){
  saveWidget(plt, file=paste0("../graphs/",deparse(substitute(plt)),".html"),
             selfcontained=FALSE, libdir="../graphs/plotlyJS", title=deparse(substitute(plt)))
}

thresholdText <- function(plt, desc, linePos, textPos){
  plt+geom_segment(x=head(stateDataCleaned$date, 1), y = linePos, xend = tail(stateDataCleaned$date, 1), yend=linePos, color="red")+
    annotate("text", x=stateDataCleaned$date[round(nrow(stateDataCleaned)/2, 0)],y=textPos, label=desc, color = 'red', size = 5)
}

numFormat <- function(num){
  return(formatC((num), format = "d", big.mark = ","))
}
```


## Rewrite daily test graph
```{r}
testData <- stateDataCleaned%>%
  select(date,posTest,negTest,Avg7Day_Tests,total=tests)%>%
  pivot_longer(c(posTest,negTest), names_to="result",values_to="numTests")

tests <- ggplot(testData, aes(date, numTests, fill=result, group=1))+
  geom_col(aes(text=paste0("Date: ", date,
                           "<br>", c("Positive", "Negative"), ": ", formatC(numTests, format = "d", big.mark = ","),
                           "<br>Total Tests: ", formatC(total, format = "d", big.mark = ","))))+
  geom_line(aes(y=Avg7Day_Tests, text=paste0("Date: ", date,
                                             "<br>7-Day Average: ", formatC(Avg7Day_Tests, format = "d", big.mark = ","))), color="blue")+
  labs(title = paste("Latest Data:", updated,
                     "\n<sup>Tests Performed:",formatC((tail(testData$total, 1)), format = "d", big.mark = ",")),
       x="Date", y="Tests Performed")+
  scale_fill_brewer(name="Result", palette="Set1")
tests <- ggArgs(tests)

tests$x$data[[1]]$name <- "Negative"
tests$x$data[[2]]$name <- "Positive"

tests
```


## Rewrite ICU graph
```{r}
ICUData <- stateDataCleaned%>%
  select(date, ICU, vent, Avg7Day_ICU, Avg7Day_Vent)%>%
  pivot_longer(c("ICU", "vent"), names_to="type", values_to="patients")

ICU <- ggplot(ICUData,aes(date, patients, fill=type, group=1))+
  geom_col(aes(text=paste0("Date: ", date,
                          "<br>", c("ICU", "Ventilator"), ": ", patients)), position="dodge")+
  geom_line(aes(y=Avg7Day_ICU, text=paste("Date: ", date,
                                          "<br>7-Day Average (ICU): ", Avg7Day_ICU)), color="blue")+
  geom_line(aes(y=Avg7Day_Vent, text=paste("Date: ", date,
                                           "<br>7-Day Average (Ventilator): ", Avg7Day_Vent)),color='blue')+
  scale_fill_brewer(name="Legend",palette="Set1")+
  labs(title = paste("Latest Data:", hospUpdated,
                     "\n<sup>ICU:", stateDataCleaned$ICU[nrow(stateDataCleaned) - 1],
                     "  |   Ventilator:", stateDataCleaned$vent[nrow(stateDataCleaned) - 1]),
       x="Date", y="ICU/Ventilator")
ICU <- ggArgs(ICU)
ICU$x$data[[1]]$name <- "ICU"
ICU$x$data[[2]]$name <- "Ventilator"

widgetArgs(ICU)

ICU
```


## Historical vaccination data
```{r}
vaxHist <- read.csv("https://raw.githubusercontent.com/youyanggu/covid19-cdc-vaccination-data/main/aggregated_adjusted.csv")%>%
  filter(Location == "RI" | Location == "CT" | Location == "MA")%>%
  select(date = Date, state = Location, dist = Doses_Distributed, admin = Doses_Administered)%>%
  filter(date >= "2021-01-04")%>%
  mutate(pct = (round((admin / dist), 4)) * 100)

vaxHist$date <- as.Date(vaxHist$date)
```

```{r}
vaxRI <- read.csv("https://raw.githubusercontent.com/youyanggu/covid19-cdc-vaccination-data/main/aggregated_adjusted.csv")%>%
  filter(Location == "RI")%>%
  select(date = Date, dist = Doses_Distributed, admin = Doses_Administered)%>%
  filter(date >= "2020-12-30")%>%
  mutate(pct = (round((admin / dist), 4)) * 100)

write.csv(vaxRI, "../export/vax-percent-RI-02-14-21.csv", row.names=FALSE)
write.csv(vaxHist, "../export/vax-percent-SNE-02-14-21.csv", row.names=FALSE)
```

```{r}
vaxPct <- ggplot(vaxHist, aes(date, pct, color = state, group=1, text = paste0("Date: ", date,
                                                                      "\nState: ", state,
                                                                      "\n% Administered: ", pct)))+
  geom_line()+
  labs(title="% Doses Administered in Southern NE", x = "Date", y = "% Doses Administered")

vaxPct <- ggArgs(vaxPct)

vaxPct

saveWidget(vaxPct, file="../export/vax-percent.html", selfcontained = TRUE, title="Vaccine Percentage (New England)")
```


